DROP SYNONYM EQSERVIZI_WEB.seq_id_mor_pol;
DROP SYNONYM EQSERVIZI_WEB.POLL_ANSWER;
DROP SYNONYM EQSERVIZI_WEB.POLL_DATA;
DROP SYNONYM EQSERVIZI_WEB.POLL_INDEX;
DROP SYNONYM EQSERVIZI_WEB.POLL_OPTION;
DROP SYNONYM EQSERVIZI_WEB.POLL_QUESTION;

CREATE SYNONYM EQSERVIZI_WEB.seq_id_mor_poll FOR EQSERVIZI.seq_id_mor_poll;

CREATE SYNONYM EQSERVIZI_WEB.POLL_ANSWER FOR EQSERVIZI.POLL_ANSWER;
CREATE SYNONYM EQSERVIZI_WEB.POLL_DATA FOR EQSERVIZI.POLL_DATA;
CREATE SYNONYM EQSERVIZI_WEB.POLL_INDEX FOR EQSERVIZI.POLL_INDEX;
CREATE SYNONYM EQSERVIZI_WEB.POLL_OPTION FOR EQSERVIZI.POLL_OPTION;
CREATE SYNONYM EQSERVIZI_WEB.POLL_QUESTION FOR EQSERVIZI.POLL_QUESTION;