alter table poll_index rename to eq_sac_poll_index;
alter table poll_data rename to eq_sac_poll_data;
alter table poll_answer rename to eq_sac_poll_answer;
alter table poll_option rename to eq_sac_poll_option;
alter table poll_question rename to eq_sac_poll_question;

DROP SYNONYM EQSERVIZI_WEB.seq_id_mor_poll;


DROP SYNONYM EQSERVIZI_WEB.POLL_ANSWER;
DROP SYNONYM EQSERVIZI_WEB.POLL_DATA;
DROP SYNONYM EQSERVIZI_WEB.POLL_INDEX;
DROP SYNONYM EQSERVIZI_WEB.POLL_OPTION;
DROP SYNONYM EQSERVIZI_WEB.POLL_QUESTION;


CREATE SYNONYM EQSERVIZI_WEB.seq_id_mor_poll FOR EQSERVIZI.EQ_SAC_seq_id_mor_poll;

CREATE SYNONYM EQSERVIZI_WEB.EQ_SAC_POLL_ANSWER FOR EQSERVIZI.EQ_SAC_POLL_ANSWER;
CREATE SYNONYM EQSERVIZI_WEB.EQ_SAC_POLL_DATA FOR EQSERVIZI.EQ_SAC_POLL_DATA;
CREATE SYNONYM EQSERVIZI_WEB.EQ_SAC_POLL_INDEX FOR EQSERVIZI.EQ_SAC_POLL_INDEX;
CREATE SYNONYM EQSERVIZI_WEB.EQ_SAC_POLL_OPTION FOR EQSERVIZI.EQ_SAC_POLL_OPTION;
CREATE SYNONYM EQSERVIZI_WEB.EQ_SAC_POLL_QUESTION FOR EQSERVIZI.EQ_SAC_POLL_QUESTION;


